name: eeve_app

description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  smooth_page_indicator: ^1.2.1
  curved_navigation_bar: ^1.0.6
  persistent_bottom_nav_bar: ^6.2.1
  introduction_screen: ^3.1.17
  pin_code_fields: ^8.0.1
  supabase_flutter: ^1.10.18
  dotted_line: ^3.2.3
  shared_preferences: ^2.5.3
  moyasar: ^2.0.1
  flutter_credit_card: 3.0.1
  http: ^1.2.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700


dependency_overrides:
  sign_in_with_apple: ^6.1.0